version: '3.8'

services:
  db:
    image: postgres:16
    container_name: identity-db
    restart: always
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  identityservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=identitydb;Username=postgres;Password=secret
    ports:
      - "8080:8080"
    volumes:
      - ./secrets:/secrets:ro

volumes:
  pgdata: