name: CI for IdentityService

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PantryCloud.IdentityService.sln

      - name: Build
        run: dotnet build PantryCloud.IdentityService.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test PantryCloud.IdentityService.sln --no-build --configuration Release --logger trx